# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 02:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobSchd', '0003_auto_20171002_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='is_fav',
        ),
    ]
