# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSchd', '0007_job_personen'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='GrpQtrEn',
            field=models.CharField(default='sgeasd', max_length=50),
            preserve_default=False,
        ),
    ]
