# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSchd', '0008_job_grpqtren'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='AggSpUN',
            field=models.CharField(default='uyreafs', max_length=50),
            preserve_default=False,
        ),
    ]
