# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSchd', '0009_job_aggspun'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='GeoAggSU',
            field=models.CharField(default='teaewfs', max_length=50),
            preserve_default=False,
        ),
    ]
