# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSchd', '0011_remove_job_aggspun'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='AggSpUN',
            field=models.CharField(default='tadf', max_length=50),
            preserve_default=False,
        ),
    ]
