# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSchd', '0012_job_aggspun'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
