# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 04:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('JobSchd', '0015_auto_20171211_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFinal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(help_text='Conneticut_Run', max_length=50)),
                ('project_name', models.CharField(help_text='Connecticut_Synthetic_Population', max_length=50)),
                ('HouseEN', models.CharField(help_text='hhld', max_length=50, verbose_name='Household Entity Name')),
                ('PersonEN', models.CharField(help_text='person', max_length=50, verbose_name='Person Entity Name')),
                ('GrpQtrEn', models.CharField(help_text='gq', max_length=50, verbose_name='Groupquater Entity Name')),
                ('AggSpUN', models.CharField(default='Region', help_text='County', max_length=50, verbose_name='Aggregate Spatial Unit')),
                ('GeoAggSU', models.CharField(default='Geo', help_text='TAZ', max_length=50, verbose_name='Disaggregate Spatial Unit')),
                ('Household_Sample_File', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Household Sample File')),
                ('Person_Sample_File', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Person Sample File')),
                ('Groupquarter_Sample_File', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Groupquarter Sample File')),
                ('Agg_Household_Marginal_File', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Aggregate Household Marginal File')),
                ('Agg_Person_Marginal_File', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Aggregate Person Marginal File')),
                ('Agg_Groupquarter_Marginal_File', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Aggregate Groupquarter Marginal File')),
                ('Geo_Household_Marginal_File', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Disaggregate Household Marginal File')),
                ('Geo_Person_Marginal_File', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Disaggregate Person Marginal File')),
                ('Geo_Groupquarter_Marginal_File', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Disaggregate Groupquarter Marginal File')),
                ('Agg_Geo_Mapping_File', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Aggregate Disaggregate Mapping File')),
                ('Sample_Agg_Mapping_File', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Sample Aggregate Mapping File')),
                ('Sample_Geo_Mapping_File', models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Sample Disaggregate Mapping File')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='job',
            old_name='file',
            new_name='File',
        ),
        migrations.AlterField(
            model_name='job',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
