# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSchd', '0017_auto_20171215_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfinal',
            name='job_name',
            field=models.CharField(help_text='Conneticut_Run', max_length=50, unique=True),
        ),
    ]
