# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobSchd', '0020_auto_20171217_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobfinal',
            name='marginals_groupquarter',
        ),
        migrations.RemoveField(
            model_name='jobfinal',
            name='marginals_household',
        ),
        migrations.RemoveField(
            model_name='jobfinal',
            name='marginals_person',
        ),
    ]
