# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 02:06
from __future__ import unicode_literals

import JobSchd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSchd', '0021_auto_20171218_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_ids',
            field=models.CharField(default='[1,2,3', help_text='[1,2,3,4,5,6,7,8,9,10,11,12,13,14]', max_length=50, verbose_name='Geo Ids'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_to_sample',
            field=models.FileField(blank=True, help_text='geo_sample_mapping.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='geo_to_sample'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='iterations',
            field=models.IntegerField(default=1, verbose_name='Iterations'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_ids',
            field=models.CharField(default='[1,2,3', help_text='[1,2,3,4,5,6,7,8,9,10,11,12,13,14]', max_length=50, verbose_name='Region Ids'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_to_geo',
            field=models.FileField(blank=True, help_text='region_geo_mapping.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='region_to_geo'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_to_sample',
            field=models.FileField(blank=True, help_text='region_sample_mapping.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='region_to_sample'),
        ),
    ]
