# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 02:48
from __future__ import unicode_literals

import JobSchd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSchd', '0024_auto_20171218_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfinal',
            name='geo_groupquarter_files',
            field=models.FileField(blank=True, help_text='groupquarters_marginals.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Geo Groupquarter'),
        ),
        migrations.AddField(
            model_name='jobfinal',
            name='geo_household_files',
            field=models.FileField(blank=True, help_text='household_marginals.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Geo Household'),
        ),
        migrations.AddField(
            model_name='jobfinal',
            name='geo_person_files',
            field=models.FileField(blank=True, help_text='person_marginals.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Geo Person'),
        ),
        migrations.AddField(
            model_name='jobfinal',
            name='region_groupquarter_files',
            field=models.FileField(blank=True, help_text='region_groupquarters_marginals.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Region Groupquarter'),
        ),
        migrations.AddField(
            model_name='jobfinal',
            name='region_household_files',
            field=models.FileField(blank=True, help_text='region_household_marginals.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Region Household'),
        ),
        migrations.AddField(
            model_name='jobfinal',
            name='region_person_files',
            field=models.FileField(blank=True, help_text='region_person_marginals.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Region Person'),
        ),
    ]
