# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-24 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSchd', '0025_auto_20171218_0248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfinal',
            name='ipf_tolerance',
            field=models.DecimalField(decimal_places=5, default=0.0001, max_digits=8, verbose_name='Tolerance'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='pvalue_tolerance',
            field=models.DecimalField(decimal_places=5, default=0.9999, max_digits=8, verbose_name='Pvalue Tolerance'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='rew_tolerance',
            field=models.DecimalField(decimal_places=5, default=0.0001, max_digits=8, verbose_name='Tolerance'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='zmc',
            field=models.DecimalField(decimal_places=5, default=1e-05, max_digits=8, verbose_name='Zero Marginal Correction'),
        ),
    ]
