# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-25 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSchd', '0026_auto_20171224_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfinal',
            name='entity_one',
            field=models.CharField(default='household', help_text='household or person', max_length=50, verbose_name='Entity'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='filename_two',
            field=models.CharField(default='rpsex_rpage.csv', help_text='hhsize_income.csv', max_length=50, verbose_name='Filename'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_groupquarter',
            field=models.CharField(default='[gqtotals, gqtype]', help_text='eg. [gqtotals, gqtype]', max_length=50, verbose_name='Geo Groupquarter'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_household',
            field=models.CharField(default='[hhtotals, hinc, hsize]', help_text='eg. [hhtotals, hinc, hsize] ', max_length=50, verbose_name='Geo Household'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_person',
            field=models.CharField(default='[pworker, ptotals]', help_text='eg. [pworker, ptotals] ', max_length=50, verbose_name='Geo Person'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='multiway_variables_two',
            field=models.CharField(default='[rpsex, rpage]', help_text='[hsize, hinc]', max_length=50, verbose_name='Multiway Variables'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='procedure',
            field=models.CharField(choices=[('IPU', 'IPU'), ('Entropy', 'Entropy')], default='ipu', max_length=50, verbose_name='Procedure'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_groupquarter',
            field=models.CharField(default='[gqrtotals]', help_text='eg. [gqrtotals]', max_length=50, verbose_name='Region Groupquarter'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_household',
            field=models.CharField(default='[hhrtotals]', help_text='eg. [hhrtotals]', max_length=50, verbose_name='Region Household'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_person',
            field=models.CharField(default='[rpsex, rpage, rpworker, prtotals]', help_text='eg. [rpsex, rpage, rpworker, prtotals]', max_length=50, verbose_name='Region Person'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='sample_geo',
            field=models.CharField(default='sample_geo', help_text='TAZ', max_length=50, verbose_name='Disaggregate Spatial Unit'),
        ),
    ]
