# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-03 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSchd', '0030_auto_20180102_0454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfinal',
            name='procedure',
            field=models.CharField(choices=[('ipu', 'IPU'), ('entropy', 'Entropy')], default='ipu', max_length=50, verbose_name='Procedure'),
        ),
    ]
