# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 18:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JobSchd', '0032_auto_20180104_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobfinal',
            name='entity_three',
        ),
        migrations.RemoveField(
            model_name='jobfinal',
            name='filename_three',
        ),
        migrations.RemoveField(
            model_name='jobfinal',
            name='filetype_three',
        ),
    ]
