# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSchd', '0035_auto_20180104_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfinal',
            name='Job_Pushed',
            field=models.BooleanField(default=True, help_text='If the Job is configured, Your updates will not be reflected , Make another Job', verbose_name='Submit'),
        ),
    ]
