# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-04 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSchd', '0037_auto_20180104_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfinal',
            name='Job_Pushed',
            field=models.BooleanField(default=True, help_text='Your updated/submited Job will be Processed by our system only if you check this option', verbose_name=' Check this option If you want to Process this New/Updated Job Now or Uncheck if you want save the data and want to run it later'),
        ),
    ]
