# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 18:23
from __future__ import unicode_literals

import JobSchd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSchd', '0039_auto_20180104_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfinal',
            name='Job_Pushed',
            field=models.BooleanField(default=True, help_text='Your updated/submited job will be Processed by our system only if you check this option.', verbose_name=' Check this option if you want to process this new/updated job now or uncheck if you want save the data and want to run it later.'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='apf',
            field=models.IntegerField(default=1, verbose_name='Parameter IPF - Archive Performance Frequency'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='collate_across_geos',
            field=models.BooleanField(default=False, verbose_name='Output Weights Collate Across Geos'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='desc',
            field=models.CharField(default='Connecticut TAZ Scenario', help_text='e.g. Connecticut TAZ Scenario', max_length=50, verbose_name='Scenario Description'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='draws_iterations',
            field=models.IntegerField(default=1, verbose_name='Parameters Draws - Iterations'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='entities',
            field=models.CharField(default='[household, groupquarter, person]', help_text='e.g. [household, groupquarter, person]', max_length=500, verbose_name='Entities'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='entity_one',
            field=models.CharField(default='household', help_text='e.g. household or person', max_length=50, verbose_name='Outputs - Entity - One'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='entity_two',
            field=models.CharField(default='person', help_text='e.g. household or person', max_length=50, verbose_name='Outputs - Entity - Two'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='export',
            field=models.BooleanField(default=True, verbose_name='Outputs Weights - Export'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='filename_one',
            field=models.CharField(default='hhsize_income.csv', help_text='e.g. hhsize_income.csv', max_length=50, verbose_name='Outputs - Filename - One'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='filename_two',
            field=models.CharField(default='rpsex_rpage.csv', help_text='e.g. rpsex_rpage.csv', max_length=50, verbose_name='Outputs - Filename - Two'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='filetype_one',
            field=models.CharField(default='csv', help_text='e.g. csv', max_length=50, verbose_name='Outputs - Filetype - One'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='filetype_two',
            field=models.CharField(default='csv', help_text='e.g. csv', max_length=50, verbose_name='Outputs - Filetype - Two'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo',
            field=models.CharField(default='geo', max_length=50, verbose_name='Geo Entity Name'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_all_ids',
            field=models.BooleanField(default=True, verbose_name='Geos To Synthesize - Geo All Ids'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_groupquarter',
            field=models.CharField(default='', help_text='e.g. [gqtotals, gqtype]', max_length=50, verbose_name='Control - Geo Groupquarter'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_groupquarter_files',
            field=models.FileField(blank=True, help_text='e.g. groupquarters_marginals.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Geo Groupquarter Marginals File'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_household',
            field=models.CharField(default='', help_text='e.g. [hhtotals, hinc, hsize]', max_length=50, verbose_name='Control - Geo Household'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_household_files',
            field=models.FileField(blank=True, help_text='e.g. household_marginals.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Geo Household Marginals File'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_ids',
            field=models.CharField(default='[1,2,3]', help_text='e.g. [1,2,3,4,5,6,7,8,9,10,11,12,13,14]', max_length=6000, verbose_name='Geos To Synthesize - Geo Ids'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_person',
            field=models.CharField(default='', help_text='e.g. [pworker, ptotals] ', max_length=50, verbose_name='Control - Geo Person'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_person_files',
            field=models.FileField(blank=True, help_text='e.g. person_marginals.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Geo Person Marginals File'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_to_sample',
            field=models.FileField(blank=True, help_text='e.g. geo_sample_mapping.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='geo to Sample File'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='hid',
            field=models.CharField(default='hid', help_text='e.g. hid', max_length=50, verbose_name='Household Entity Name'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='housing_entities',
            field=models.CharField(default='[household, groupquarter]', help_text='e.g. [household, groupquarter]', max_length=500, verbose_name='Housing Entities'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='inner_iterations',
            field=models.IntegerField(default=1, verbose_name='Parameter Reweighting - Inner Iterations'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='ipf_tolerance',
            field=models.DecimalField(decimal_places=5, default=0.0001, max_digits=7, verbose_name='Parameter IPF - Tolerance'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='iterations',
            field=models.IntegerField(default=1, verbose_name='Parameter IPF - Iterations'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='job_name',
            field=models.CharField(help_text='e.g. Connecticut_Run', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='multiway_variables_one',
            field=models.CharField(default='[hsize, hinc]', help_text='e.g. [hsize, hinc]', max_length=50, verbose_name='Outputs - Multiway Variables - One'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='multiway_variables_two',
            field=models.CharField(default='[hsize, hinc]', help_text='e.g. [rpsex, rpage]', max_length=50, verbose_name='Outputs - Multiway Variables - Two'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='outer_iterations',
            field=models.IntegerField(default=1000, verbose_name='Parameter Reweighting - Outer Iterations'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='performance',
            field=models.CharField(default='[ipf, reweighting, drawing]', help_text='e.g.[ipf, reweighting, drawing]', max_length=50, verbose_name='Outputs - Performance'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='person_entities',
            field=models.CharField(default='[person]', help_text='e.g. [person]', max_length=500, verbose_name='Person Entity'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='pid',
            field=models.CharField(default='pid', help_text='e.g. pid', max_length=50, verbose_name='Person Entity Name'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='procedure',
            field=models.CharField(choices=[('ipu', 'IPU'), ('entropy', 'Entropy')], default='ipu', max_length=50, verbose_name='Parameter Reweighting - Procedure'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='project_name',
            field=models.CharField(help_text='e.g. Connecticut_Synthetic_Population', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='pvalue_tolerance',
            field=models.DecimalField(decimal_places=5, default=0.9999, max_digits=7, verbose_name='Parameters Draws - p-value Tolerance'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='rapf',
            field=models.IntegerField(default=1, verbose_name='Parameter Reweighting - Archive Performance Frequency'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region',
            field=models.CharField(default='region', max_length=50, verbose_name='Aggregate Spatial Unit'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_all_ids',
            field=models.BooleanField(default=True, verbose_name='Geos To Synthesize - Region All Ids'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_groupquarter',
            field=models.CharField(default='', help_text='e.g. [gqrtotals]', max_length=50, verbose_name='Control - Region Groupquarter'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_groupquarter_files',
            field=models.FileField(blank=True, help_text='e.g. region_groupquarters_marginals.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Region Groupquarter Marginals File'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_household',
            field=models.CharField(default='', help_text='e.g. [hhrtotals]', max_length=50, verbose_name='Control - Region Household'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_household_files',
            field=models.FileField(blank=True, help_text='e.g. region_household_marginals.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Region Household Marginals File'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_ids',
            field=models.CharField(default='[1,2,3]', help_text='e.g. [1,2,3,4,5,6,7,8,9,10,11,12,13,14]', max_length=6000, verbose_name='Geos To Synthesize - Region Ids'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_person',
            field=models.CharField(default='', help_text='e.g. [rpsex, rpage, rpworker, prtotals]', max_length=50, verbose_name='Control - Region Person'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_person_files',
            field=models.FileField(blank=True, help_text='e.g. region_person_marginals.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Region Person Marginals File'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_to_geo',
            field=models.FileField(blank=True, help_text='e.g. region_geo_mapping.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='region to Geo File'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_to_sample',
            field=models.FileField(blank=True, help_text='e.g. region_sample_mapping.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='region to Sample File'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='rew_tolerance',
            field=models.DecimalField(decimal_places=5, default=0.0001, max_digits=7, verbose_name='Parameter Reweighting - Tolerance'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='rp',
            field=models.CharField(choices=[('bucket', 'Bucket')], default='bucket', max_length=50, verbose_name='Parameter IPF - Rounding Procedure'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='sample_geo',
            field=models.CharField(default='sample_geo', max_length=50, verbose_name='Disaggregate Spatial Unit'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='sample_groupquarter',
            field=models.FileField(blank=True, help_text='e.g. groupquarters_sample.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Sample Groupquarter File'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='sample_household',
            field=models.FileField(blank=True, help_text='e.g. household_sample.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Sample Household File'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='sample_person',
            field=models.FileField(blank=True, help_text='e.g. person_sample.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Sample Person File'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='seed',
            field=models.IntegerField(default=0, verbose_name='Parameters Draws - Seed'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='zmc',
            field=models.DecimalField(decimal_places=5, default=1e-05, max_digits=7, verbose_name='Parameter IPF - Zero Marginal Correction'),
        ),
    ]
