# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-06 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSchd', '0040_auto_20180106_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfinal',
            name='multiway_variables_two',
            field=models.CharField(default='[rpsex, rpage]', help_text='e.g. [rpsex, rpage]', max_length=50, verbose_name='Outputs - Multiway Variables - Two'),
        ),
    ]
