# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-13 03:35
from __future__ import unicode_literals

import JobSchd.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('JobSchd', '0041_auto_20180106_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfinal',
            name='entity_three',
            field=models.CharField(default='person', help_text='household or person', max_length=50, verbose_name='Entity'),
        ),
        migrations.AddField(
            model_name='jobfinal',
            name='filename_three',
            field=models.CharField(default='hhsize_income.csv', help_text='hhsize_income.csv', max_length=50, verbose_name='Filename'),
        ),
        migrations.AddField(
            model_name='jobfinal',
            name='filetype_three',
            field=models.CharField(default='csv', help_text='csv', max_length=50, verbose_name='Filetype'),
        ),
        migrations.AddField(
            model_name='jobfinal',
            name='job_create_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobfinal',
            name='job_status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Yaml Error', 'Yaml Error'), ('System Error', 'System Error'), ('Completed', 'Completed'), ('In-Progress', 'In-Progress')], default='Completed', max_length=30, verbose_name='Job Status'),
        ),
        migrations.AddField(
            model_name='jobfinal',
            name='job_update_time',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='jobfinal',
            name='op_file_url',
            field=models.CharField(default='#', max_length=500),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='Job_Pushed',
            field=models.BooleanField(default=False, help_text='If the Job is configured, Your updates will not be reflected , Make another Job', verbose_name='Is Job Is configured'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='apf',
            field=models.IntegerField(default=1, verbose_name='Archive Performance Frequency'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='collate_across_geos',
            field=models.BooleanField(default=False, verbose_name='Collate Across Geos'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='desc',
            field=models.CharField(default='Connecticut TAZ Scenario', help_text='Connecticut TAZ Scenario', max_length=50, verbose_name='Scenario Description'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='draws_iterations',
            field=models.IntegerField(default=1, verbose_name='Iterations'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='entities',
            field=models.CharField(default='[household, groupquarter, person]', help_text='[household, groupquarter, person]', max_length=500, verbose_name='Entities'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='entity_one',
            field=models.CharField(default='person', help_text='household or person', max_length=50, verbose_name='Entity'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='entity_two',
            field=models.CharField(default='person', help_text='household or person', max_length=50, verbose_name='Entity'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='export',
            field=models.BooleanField(default=True, verbose_name='Export'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='filename_one',
            field=models.CharField(default='hhsize_income.csv', help_text='hhsize_income.csv', max_length=50, verbose_name='Filename'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='filename_two',
            field=models.CharField(default='hhsize_income.csv', help_text='hhsize_income.csv', max_length=50, verbose_name='Filename'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='filetype_one',
            field=models.CharField(default='csv', help_text='csv', max_length=50, verbose_name='Filetype'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='filetype_two',
            field=models.CharField(default='csv', help_text='csv', max_length=50, verbose_name='Filetype'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo',
            field=models.CharField(default='geo', help_text='TAZ', max_length=50, verbose_name='Groupquater Entity Name'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_all_ids',
            field=models.BooleanField(default=True, verbose_name='Geo All Ids'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_groupquarter',
            field=models.CharField(default='', help_text='eg. [gqtotals, gqtype]', max_length=50, verbose_name='Geo Groupquarter'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_groupquarter_files',
            field=models.FileField(blank=True, help_text='groupquarters_marginals.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Geo Groupquarter'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_household',
            field=models.CharField(default='', help_text='eg. [hhtotals, hinc, hsize]', max_length=50, verbose_name='Geo Household'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_household_files',
            field=models.FileField(blank=True, help_text='household_marginals.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Geo Household'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_ids',
            field=models.CharField(default='[1,2,3]', help_text='[1,2,3,4,5,6,7,8,9,10,11,12,13,14]', max_length=50, verbose_name='Geo Ids'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_person',
            field=models.CharField(default='', help_text='eg. [pworker, ptotals] ', max_length=50, verbose_name='Geo Person'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_person_files',
            field=models.FileField(blank=True, help_text='person_marginals.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Geo Person'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_to_sample',
            field=models.FileField(blank=True, help_text='geo_sample_mapping.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='geo to sample'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='hid',
            field=models.CharField(default='hid', help_text='hhld', max_length=50, verbose_name='Household Entity Name'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='housing_entities',
            field=models.CharField(default='[household, groupquarter]', help_text='[household, groupquarter]', max_length=500, verbose_name='Housing Entities'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='inner_iterations',
            field=models.IntegerField(default=1, verbose_name='Inner Iterations'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='ipf_tolerance',
            field=models.DecimalField(decimal_places=5, default=0.0001, max_digits=7, verbose_name='Tolerance'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='iterations',
            field=models.IntegerField(default=1, verbose_name='Iterations'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='job_name',
            field=models.CharField(help_text='Conneticut_Run', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='multiway_variables_one',
            field=models.CharField(default='[hsize, hinc]', help_text='[hsize, hinc]', max_length=50, verbose_name='Multiway Variables'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='multiway_variables_two',
            field=models.CharField(default='[hsize, hinc]', help_text='[hsize, hinc]', max_length=50, verbose_name='Multiway Variables'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='outer_iterations',
            field=models.IntegerField(default=1000, verbose_name='Outer Iterations'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='performance',
            field=models.CharField(default='[ipf, reweighting, drawing]', help_text='[ipf, reweighting, drawing]', max_length=50, verbose_name='Performance'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='person_entities',
            field=models.CharField(default='[person]', help_text='[person]', max_length=500, verbose_name='Person Entities'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='pid',
            field=models.CharField(default='pid', help_text='person', max_length=50, verbose_name='Person Entity Name'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='procedure',
            field=models.CharField(choices=[('IPU', 'IPU'), ('Entropy', 'Entropy')], default='IPU', max_length=50, verbose_name='Procedure'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='project_name',
            field=models.CharField(help_text='Connecticut_Synthetic_Population', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='pvalue_tolerance',
            field=models.DecimalField(decimal_places=5, default=0.9999, max_digits=7, verbose_name='Pvalue Tolerance'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='rapf',
            field=models.IntegerField(default=1, verbose_name='Archive Performance Frequency'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region',
            field=models.CharField(default='region', help_text='County', max_length=50, verbose_name='Aggregate Spatial Unit'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_all_ids',
            field=models.BooleanField(default=True, verbose_name='Region All Ids'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_groupquarter',
            field=models.CharField(default='', help_text='eg. [gqrtotals]', max_length=50, verbose_name='Region Groupquarter'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_groupquarter_files',
            field=models.FileField(blank=True, help_text='region_groupquarters_marginals.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Region Groupquarter'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_household',
            field=models.CharField(default='', help_text='eg. [hhrtotals]', max_length=50, verbose_name='Region Household'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_household_files',
            field=models.FileField(blank=True, help_text='region_household_marginals.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Region Household'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_ids',
            field=models.CharField(default='[1,2,3]', help_text='[1,2,3,4,5,6,7,8,9,10,11,12,13,14]', max_length=50, verbose_name='Region Ids'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_person',
            field=models.CharField(default='', help_text='eg. [rpsex, rpage, rpworker, prtotals]', max_length=50, verbose_name='Region Person'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_person_files',
            field=models.FileField(blank=True, help_text='region_person_marginals.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Region Person'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_to_geo',
            field=models.FileField(blank=True, help_text='region_geo_mapping.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='region to geo'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_to_sample',
            field=models.FileField(blank=True, help_text='region_sample_mapping.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='region to sample'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='rew_tolerance',
            field=models.DecimalField(decimal_places=5, default=0.0001, max_digits=7, verbose_name='Tolerance'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='rp',
            field=models.CharField(choices=[('bucket', 'bucket')], default='bucket', max_length=50, verbose_name='Rounding Procedure'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='sample_geo',
            field=models.CharField(default='geo', help_text='TAZ', max_length=50, verbose_name='Disaggregate Spatial Unit'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='sample_groupquarter',
            field=models.FileField(blank=True, help_text='groupquarters_sample.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Sample Groupquarter'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='sample_household',
            field=models.FileField(blank=True, help_text='household_sample.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Sample Household'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='sample_person',
            field=models.FileField(blank=True, help_text='person_sample.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Sample Person'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='seed',
            field=models.IntegerField(default=0, verbose_name='Seed'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='zmc',
            field=models.DecimalField(decimal_places=5, default=1e-05, max_digits=7, verbose_name='Zero Marginal Correction'),
        ),
    ]
