# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-14 06:16
from __future__ import unicode_literals

import JobSchd.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSchd', '0042_auto_20180113_0335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobfinal',
            name='entity_three',
        ),
        migrations.RemoveField(
            model_name='jobfinal',
            name='filename_three',
        ),
        migrations.RemoveField(
            model_name='jobfinal',
            name='filetype_three',
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='Job_Pushed',
            field=models.BooleanField(default=False, help_text='Check this option if you want the system to run job now, If you just want to save the job keep it UnCheck', verbose_name='Submit/Save Job'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='apf',
            field=models.IntegerField(default=1, verbose_name='Parameters IPF Archive Performance Frequency'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='arc',
            field=models.BooleanField(default=True, verbose_name='Scenario Apply Region Controls'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='collate_across_geos',
            field=models.BooleanField(default=False, verbose_name='Output Weights Collate Across Geos'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='desc',
            field=models.CharField(default='Connecticut TAZ Scenario', help_text='e.g. Connecticut TAZ Scenario', max_length=50, verbose_name='Scenario Description'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='draws_iterations',
            field=models.IntegerField(default=1, verbose_name='Parameters Draws Iterations'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='entities',
            field=models.CharField(default='[household, groupquarter, person]', help_text='e.g. [household, groupquarter, person]', max_length=500, verbose_name='Entities'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='entity_one',
            field=models.CharField(default='household', help_text='e.g. household or person', max_length=50, verbose_name='Output Entity'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='entity_two',
            field=models.CharField(default='person', help_text='e.g. household or person', max_length=50, verbose_name='Output Entity'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='export',
            field=models.BooleanField(default=True, verbose_name='Output Weights Export'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='filename_one',
            field=models.CharField(default='hhsize_income.csv', help_text='e.g. hhsize_income.csv', max_length=50, verbose_name='Output Filename'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='filename_two',
            field=models.CharField(default='rpsex_rpage.csv', help_text='e.g. rpsex_rpage.csv', max_length=50, verbose_name='Output Filename'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='filetype_one',
            field=models.CharField(default='csv', help_text='e.g. csv', max_length=50, verbose_name='Output Filetype'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='filetype_two',
            field=models.CharField(default='csv', help_text='e.g. csv', max_length=50, verbose_name='Output Filetype'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo',
            field=models.CharField(default='geo', max_length=50, verbose_name='Groupquaters Entity Name'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_all_ids',
            field=models.BooleanField(default=True, verbose_name='Geos To Synthesize Geo All Ids'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_groupquarter',
            field=models.CharField(default='', help_text='e.g.  [gqtotals, gqtype]', max_length=50, verbose_name='Control Variable Geo Groupquarter'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_groupquarter_files',
            field=models.FileField(blank=True, help_text='e.g. groupquarters_marginals.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Geo Groupquarter Marginals'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_household',
            field=models.CharField(default='', help_text='e.g.  [hhtotals, hinc, hsize]', max_length=50, verbose_name='Control Variable Geo Household'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_household_files',
            field=models.FileField(blank=True, help_text='e.g. household_marginals.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Geo Household Marginals'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_ids',
            field=models.CharField(default='[1,2,3]', help_text='e.g. [1,2,3,4,5,6,7,8,9,10,11,12,13,14]', max_length=50, verbose_name='Geos To Synthesize Geo Ids'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_person',
            field=models.CharField(default='', help_text='e.g.  [pworker, ptotals] ', max_length=50, verbose_name='Control Variable Geo Person'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_person_files',
            field=models.FileField(blank=True, help_text='e.g. person_marginals.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Geo Person Marginals'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_to_sample',
            field=models.FileField(blank=True, help_text='e.g. geo_sample_mapping.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='geo to Sample'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='hid',
            field=models.CharField(default='hid', help_text='e.g. hhld', max_length=50, verbose_name='Household Entity Name'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='housing_entities',
            field=models.CharField(default='[household, groupquarter]', help_text='e.g. [household, groupquarter]', max_length=500, verbose_name='Housing Entities'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='inner_iterations',
            field=models.IntegerField(default=1, verbose_name='Parameters Reweighting Inner Iterations'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='ipf_tolerance',
            field=models.DecimalField(decimal_places=5, default=0.0001, max_digits=7, verbose_name='Parameters IPF Tolerance'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='iterations',
            field=models.IntegerField(default=1, verbose_name='Parameters IPF Iterations'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='job_name',
            field=models.CharField(help_text='e.g. Conneticut_Run', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='job_status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Yaml-Error', 'Yaml-Error'), ('System-Error', 'System-Error'), ('Completed', 'Completed'), ('In-Progress', 'In-Progress')], default='Submitted', max_length=30, verbose_name='Job Status'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='multiway_variables_one',
            field=models.CharField(default='[hsize, hinc]', help_text='e.g. [hsize, hinc]', max_length=50, verbose_name='Output Multiway Variables'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='multiway_variables_two',
            field=models.CharField(default='[rpsex, rpage]', help_text='e.g. [rpsex, rpage]', max_length=50, verbose_name='Output Multiway Variables'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='outer_iterations',
            field=models.IntegerField(default=1000, verbose_name='Parameters Reweighting Outer Iterations'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='performance',
            field=models.CharField(default='[ipf, reweighting, drawing]', help_text='e.g. [ipf, reweighting, drawing]', max_length=50, verbose_name='Output Performance'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='person_entities',
            field=models.CharField(default='[person]', help_text='e.g. [person]', max_length=500, verbose_name='Person Entity'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='pid',
            field=models.CharField(default='pid', help_text='e.g. person', max_length=50, verbose_name='Person Entity Name'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='procedure',
            field=models.CharField(choices=[('IPU', 'IPU'), ('Entropy', 'Entropy')], default='IPU', max_length=50, verbose_name='Parameters Reweighting Procedure'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='project_name',
            field=models.CharField(help_text='e.g. Connecticut_Synthetic_Population', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='pvalue_tolerance',
            field=models.DecimalField(decimal_places=5, default=0.9999, max_digits=7, verbose_name='Parameters Draws Pvalue Tolerance'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='rapf',
            field=models.IntegerField(default=1, verbose_name='Parameters Reweighting Archive Performance Frequency'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region',
            field=models.CharField(default='region', max_length=50, verbose_name='Aggregate Spatial Unit'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_all_ids',
            field=models.BooleanField(default=True, verbose_name='Geos To Synthesize Region All Ids'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_groupquarter',
            field=models.CharField(default='', help_text='e.g.  [gqrtotals]', max_length=50, verbose_name='Control Variable Region Groupquarter'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_groupquarter_files',
            field=models.FileField(blank=True, help_text='e.g. region_groupquarters_marginals.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Region Groupquarter Marginals'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_household',
            field=models.CharField(default='', help_text='e.g.  [hhrtotals]', max_length=50, verbose_name='Control Variable Region Household'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_household_files',
            field=models.FileField(blank=True, help_text='e.g. region_household_marginals.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Region Household Marginals'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_ids',
            field=models.CharField(default='[1,2,3]', help_text='e.g. [1,2,3,4,5,6,7,8,9,10,11,12,13,14]', max_length=50, verbose_name='Geos To Synthesize Region Ids'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_person',
            field=models.CharField(default='', help_text='e.g.  [rpsex, rpage, rpworker, prtotals]', max_length=50, verbose_name='Control Variable Region Person'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_person_files',
            field=models.FileField(blank=True, help_text='e.g. region_person_marginals.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Region Person Marginals'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_to_geo',
            field=models.FileField(blank=True, help_text='e.g. region_geo_mapping.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='region to Geo'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_to_sample',
            field=models.FileField(blank=True, help_text='e.g. region_sample_mapping.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='region to Sample'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='rew_tolerance',
            field=models.DecimalField(decimal_places=5, default=0.0001, max_digits=7, verbose_name='Parameters Reweighting Tolerance'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='rp',
            field=models.CharField(choices=[('bucket', 'bucket')], default='bucket', max_length=50, verbose_name='Parameters IPF Rounding Procedure'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='sample_geo',
            field=models.CharField(default='geo', max_length=50, verbose_name='Disaggregate Spatial Unit'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='sample_groupquarter',
            field=models.FileField(blank=True, help_text='e.g. groupquarters_sample.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Sample Groupquarter'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='sample_household',
            field=models.FileField(blank=True, help_text='e.g. household_sample.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Sample Household'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='sample_person',
            field=models.FileField(blank=True, help_text='e.g. person_sample.csv', null=True, upload_to=JobSchd.models.user_directory_path, verbose_name='Sample Person'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='seed',
            field=models.IntegerField(default=0, verbose_name='Parameters Draws Seed'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='zmc',
            field=models.DecimalField(decimal_places=5, default=1e-05, max_digits=7, verbose_name='Parameters IPF Zero Marginal Correction'),
        ),
    ]
