# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-19 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSchd', '0043_auto_20180114_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfinal',
            name='procedure',
            field=models.CharField(choices=[('ipu', 'IPU'), ('entropy', 'Entropy')], default='IPU', max_length=50, verbose_name='Parameters Reweighting Procedure'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='rp',
            field=models.CharField(choices=[('bucket', 'Bucket')], default='bucket', max_length=50, verbose_name='Parameters IPF Rounding Procedure'),
        ),
    ]
