# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-24 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JobSchd', '0045_auto_20180119_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfinal',
            name='geo_ids',
            field=models.CharField(default='[1,2,3]', help_text='e.g. [1,2,3,4,5,6,7,8,9,10,11,12,13,14]', max_length=6000, verbose_name='Geos To Synthesize Geo Ids'),
        ),
        migrations.AlterField(
            model_name='jobfinal',
            name='region_ids',
            field=models.CharField(default='[1,2,3]', help_text='e.g. [1,2,3,4,5,6,7,8,9,10,11,12,13,14]', max_length=6000, verbose_name='Geos To Synthesize Region Ids'),
        ),
    ]
