#!/usr/bin/env python
import shutil

def zip(path):
    print path
    
    file_name_st=str(path).split("/")
    file_name=file_name_st[len(file_name_st)-1]

    op_path='/home/ubuntu/inbound/'+file_name    
    shutil.make_archive(op_path, 'zip', path)

#zip('/home/sumit/Dropbox/PopGen/file/sumit/Conneticut_Run')
